#!/bin/bash
exec 2>&1

. /opt/default-values.sh

exec /usr/bin/Xvnc :1 \
                   -geometry ${VNC_RESOLUTION} \
                   -depth 24 \
                   -rfbwait 30000 \
                   -${VNC_SECURITY} \
                   -rfbport 5900 \
                   -bs \
                   -ac \
                   -pn \
                   -fp /usr/share/fonts/X11/misc/,/usr/share/fonts/X11/75dpi/,/usr/share/fonts/X11/100dpi/ \
                   -dpi 100 \
                   -desktop "qBittorrent"
